#version 430 core

struct PStruct
{
	vec3 position;
	vec3 velocity;
	vec2 lifespan;
};

layout(std430, binding=0) buffer Particles
{
	PStruct particles[];
};

layout( local_size_x = 128, local_size_y = 1, local_size_z = 1 ) in;

void main(void)
{
	uint pid = gl_GlobalInvocationID.x;

	particles[pid].position.x += particles[pid].velocity.x;  
	particles[pid].position.y += particles[pid].velocity.y;
	particles[pid].position.z += particles[pid].velocity.z;

	particles[pid].lifespan.x -= 0.1;
}